// Mocks generated by Mockito 5.4.4 from annotations
// in news_app/test/features/presentation/article/bloc/article_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/app/core/errors/failure.dart' as _i6;
import 'package:news_app/app/core/usecase/usecase.dart' as _i9;
import 'package:news_app/app/features/article/domain/entitites/article.dart'
    as _i7;
import 'package:news_app/app/features/article/domain/repositories/article_repositories.dart'
    as _i2;
import 'package:news_app/app/features/article/domain/usecases/get_local_articles_usecase.dart'
    as _i8;
import 'package:news_app/app/features/article/domain/usecases/get_remote_articles_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArticleRepositories_0 extends _i1.SmartFake
    implements _i2.ArticleRepositories {
  _FakeArticleRepositories_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRemoteArticlesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRemoteArticlesUsecase extends _i1.Mock
    implements _i4.GetRemoteArticlesUsecase {
  @override
  _i2.ArticleRepositories get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeArticleRepositories_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeArticleRepositories_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ArticleRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>> call(
          _i4.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>>);
}

/// A class which mocks [GetLocalArticlesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocalArticlesUsecase extends _i1.Mock
    implements _i8.GetLocalArticlesUsecase {
  @override
  _i2.ArticleRepositories get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeArticleRepositories_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeArticleRepositories_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ArticleRepositories);

  @override
  set repository(_i2.ArticleRepositories? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Article>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>>);
}
